import os
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))

def detect_with_llm(text: str) -> float:
    """
    Uses Groq LLM to assess whether text is AI-generated.
    Returns a float between 0 (human) and 1 (AI).
    """
    prompt = f"""You are an expert at detecting whether text was written by a human or generated by an AI writing tool.

Analyze the following text and return ONLY a single number between 0.0 and 1.0:
- 0.0 means you are certain it was written by a human
- 1.0 means you are certain it was generated by AI
- Values in between reflect your uncertainty

Consider: overly smooth transitions, uniform sentence length, hedging phrases, corporate-speak, lack of personal voice, unnaturally balanced structure.

Text to analyze:
\"\"\"
{text}
\"\"\"

Respond with ONLY the number. No explanation. No other text."""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=10,
        temperature=0.1,
    )

    raw = response.choices[0].message.content.strip()

    try:
        score = float(raw)
        return max(0.0, min(1.0, score))
    except ValueError:
        return 0.5