def generate_label(attribution: str, confidence: float) -> str:
    """
    Maps attribution + confidence to a human-readable transparency label.
    Returns the exact label text shown to platform users.
    """

    confidence_pct = round(confidence * 100)

    if attribution == "likely_ai":
        return (
            f"⚠️ AI-Generated Content Detected — Our analysis suggests this content "
            f"was likely generated by an AI writing tool (confidence: {confidence_pct}%). "
            f"This label is based on automated detection and may not be perfect. "
            f"If you believe this is incorrect, you can submit an appeal."
        )

    elif attribution == "uncertain":
        return (
            f"🔍 Attribution Unclear — Our analysis was unable to determine with confidence "
            f"whether this content was written by a human or generated by an AI tool "
            f"(confidence: {confidence_pct}%). We've flagged it for transparency. "
            f"If you are the human author, you can submit an appeal to provide context."
        )

    else:  # likely_human
        return (
            f"✅ Likely Human-Written — Our analysis suggests this content was written "
            f"by a human (confidence: {confidence_pct}%). Attribution signals did not "
            f"detect significant markers of AI-generated text."
        )